loki_endpoint: "http://10.10.10.2:3100"
loki_tenant_endpoint: "http://10.10.10.2:3101"
node_agent_binary_path: "{{ playbook_dir }}/../bin/node-agent"
dbadmin_proxy_binary_path: "{{ playbook_dir }}/../bin/dbadmin-proxy"
ssh_ca_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgw0Nti8wIQWOyeZblaxUE2z9wcE/tNFowUbKXqdUEg hosting-platform-ca"

# Node identity (previously set by Terraform cloud-init)
temporal_address: "10.10.10.2:7233"
region_id: "dev"
cluster_id: "vm-cluster-1"
controlplane_ip: "10.10.10.2"
core_api_url: "http://10.10.10.2:8090/api/v1"
core_api_token: "hst_dev_e2e_test_key_00000000"
node_id: "{{ inventory_hostname }}"

# Ceph â€” must match terraform/variables.tf defaults.
# Generate new values with: just gen-ceph-keys
ceph_fsid: "481a00a9-12b6-4bf9-9d00-67861af03e06"
ceph_web_key: "AQAAAAAAAAAAABAAt2/TZjzN7KpLOvQT0y8dfA=="
storage_node_ip: "10.10.10.50"
