loki_endpoint: "http://10.10.10.2:3100"
loki_tenant_endpoint: "http://10.10.10.2:3101"
node_agent_binary_path: "{{ playbook_dir }}/../bin/node-agent"
dbadmin_proxy_binary_path: "{{ playbook_dir }}/../bin/dbadmin-proxy"
ssh_ca_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE4GO9N3r0vyVFclRw8hfHAmy7pmaTSG3MbtD5wrxYAB hosting-platform-ca"
