# Additional Vector sources for DNS nodes.

[sources.journald_pdns]
type = "journald"
include_units = ["pdns"]

[transforms.label_pdns]
type = "remap"
inputs = ["journald_pdns"]
source = '''
.service = "powerdns"
.level = "info"
'''

[sinks.loki_dns]
type = "loki"
inputs = ["label_pdns"]
endpoint = "http://10.10.10.2:3100"
encoding.codec = "text"

[sinks.loki_dns.labels]
service = "{{ service }}"
hostname = "{{ host }}"
level = "{{ level }}"
job = "powerdns"
