apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: headlamp
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: headlamp
spec:
  type: ClusterIP
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
      name: http
  selector:
    app: headlamp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: headlamp
      containers:
        - name: headlamp
          image: ghcr.io/kubernetes-sigs/headlamp:latest
          args:
            - "-in-cluster"
            - "-plugins-dir=/headlamp/plugins"
            - "-oidc-client-id=${HEADLAMP_CLIENT_ID}"
            - "-oidc-client-secret=$(OIDC_CLIENT_SECRET)"
            - "-oidc-idp-issuer-url=${OIDC_ISSUER_URL}"
            - "-oidc-scopes=openid,email,profile"
          envFrom:
            - secretRef:
                name: oidc-credentials
          ports:
            - containerPort: 4466
