apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: control-plane
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
    - host: admin.hosting.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hosting-admin-ui
                port:
                  number: 3001
    - host: api.hosting.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hosting-core-api
                port:
                  number: 8090
    - host: temporal.hosting.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-ui
                port:
                  number: 8080
    - host: grafana.hosting.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: prometheus.hosting.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
    - host: loki.hosting.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki
                port:
                  number: 3100
