apiVersion: v1
kind: Secret
metadata:
  name: oidc-credentials
type: Opaque
stringData:
  OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}"
  OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
  OIDC_TENANT_ID: "${OIDC_TENANT_ID}"
