apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
spec:
  type: ClusterIP
  ports:
    - port: 8233
      targetPort: 8233
      protocol: TCP
      name: http
  selector:
    app: temporal-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      enableServiceLinks: false
      containers:
        - name: temporal-ui
          image: temporalio/ui:latest
          ports:
            - containerPort: 8233
          env:
            - name: TEMPORAL_ADDRESS
              value: "127.0.0.1:7233"
            - name: TEMPORAL_UI_PORT
              value: "8233"
            - name: TEMPORAL_CSRF_COOKIE_INSECURE
              value: "true"
            - name: TEMPORAL_AUTH_ENABLED
              value: "true"
            - name: TEMPORAL_AUTH_PROVIDER_URL
              value: "${OIDC_ISSUER_URL}"
            - name: TEMPORAL_AUTH_CLIENT_ID
              value: "${TEMPORAL_CLIENT_ID}"
            - name: TEMPORAL_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: OIDC_CLIENT_SECRET
            - name: TEMPORAL_AUTH_CALLBACK_URL
              value: "https://temporal.${BASE_DOMAIN}/auth/sso/callback"
            - name: TEMPORAL_AUTH_SCOPES
              value: "openid"
