{{- if .Values.controlpanelApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hosting.fullname" . }}-controlpanel-api
  labels:
    {{- include "hosting.labels" . | nindent 4 }}
    app.kubernetes.io/component: controlpanel-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.controlpanelApi.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hosting.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controlpanel-api
{{- end }}
