{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hosting.fullname" . }}
  labels:
    {{- include "hosting.labels" . | nindent 4 }}
type: Opaque
stringData:
  CORE_DATABASE_URL: {{ .Values.secrets.coreDatabaseUrl | quote }}
  POWERDNS_DATABASE_URL: {{ .Values.secrets.powerdnsDatabaseUrl | quote }}
  STALWART_ADMIN_TOKEN: {{ .Values.secrets.stalwartAdminToken | quote }}
{{- end }}
