global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'core-api'
    static_configs:
      - targets: ['core-api:8090']
    metrics_path: /metrics

  - job_name: 'node-agent'
    static_configs:
      - targets: ['node-agent:9100']

  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8404']
    metrics_path: /stats
    params:
      stats: ['prometheus']
